import type { Theme } from '../../../shared/types';

export const catppuccinThemes: Theme[] = [
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    isDark: false,
    colors: {
      background: '#eff1f5',
      text: '#4c4f69',
      h1: '#d20f39',
      h2: '#df8e1d',
      h3: '#40a02b',
      h4: '#1e66f5',
      h5: '#8839ef',
      h6: '#ea76cb',
      link: '#1e66f5',
      linkHover: '#04a5e5',
      codeBackground: '#e6e9ef',
      codeText: '#4c4f69',
      inlineCodeBackground: '#dce0e8',
      inlineCodeText: '#d20f39',
      blockquoteBorder: '#8839ef',
      blockquoteText: '#6c6f85',
      blockquoteBackground: '#e6e9ef',
      listMarker: '#1e66f5',
      tableBorder: '#ccd0da',
      tableHeaderBackground: '#e6e9ef',
      tableRowEvenBackground: '#eff1f5',
      horizontalRule: '#ccd0da',
      bold: '#4c4f69',
      italic: '#8839ef',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    isDark: true,
    colors: {
      background: '#1e1e2e',
      text: '#cdd6f4',
      h1: '#f38ba8',
      h2: '#fab387',
      h3: '#a6e3a1',
      h4: '#89b4fa',
      h5: '#cba6f7',
      h6: '#f5c2e7',
      link: '#89b4fa',
      linkHover: '#89dceb',
      codeBackground: '#181825',
      codeText: '#cdd6f4',
      inlineCodeBackground: '#313244',
      inlineCodeText: '#f38ba8',
      blockquoteBorder: '#cba6f7',
      blockquoteText: '#a6adc8',
      blockquoteBackground: '#181825',
      listMarker: '#89b4fa',
      tableBorder: '#45475a',
      tableHeaderBackground: '#181825',
      tableRowEvenBackground: '#1e1e2e',
      horizontalRule: '#45475a',
      bold: '#cdd6f4',
      italic: '#cba6f7',
    },
  },
];
