import type { Theme } from '../../../shared/types';

export const retroThemes: Theme[] = [
  {
    id: 'synthwave-84',
    name: "Synthwave '84",
    isDark: true,
    colors: {
      background: '#262335',
      text: '#ffffff',
      h1: '#ff7edb',
      h2: '#fede5d',
      h3: '#72f1b8',
      h4: '#36f9f6',
      h5: '#f97e72',
      h6: '#ff8b39',
      link: '#36f9f6',
      linkHover: '#72f1b8',
      codeBackground: '#1e1a2e',
      codeText: '#ffffff',
      inlineCodeBackground: '#34294f',
      inlineCodeText: '#ff7edb',
      blockquoteBorder: '#ff7edb',
      blockquoteText: '#848bbd',
      blockquoteBackground: '#1e1a2e',
      listMarker: '#ff7edb',
      tableBorder: '#34294f',
      tableHeaderBackground: '#1e1a2e',
      tableRowEvenBackground: '#2a2139',
      horizontalRule: '#34294f',
      bold: '#ffffff',
      italic: '#fede5d',
    },
  },
  {
    id: 'palenight',
    name: 'Palenight',
    isDark: true,
    colors: {
      background: '#292d3e',
      text: '#a6accd',
      h1: '#f07178',
      h2: '#ffcb6b',
      h3: '#c3e88d',
      h4: '#82aaff',
      h5: '#c792ea',
      h6: '#89ddff',
      link: '#82aaff',
      linkHover: '#89ddff',
      codeBackground: '#1b1e2b',
      codeText: '#a6accd',
      inlineCodeBackground: '#3a3f58',
      inlineCodeText: '#f07178',
      blockquoteBorder: '#c792ea',
      blockquoteText: '#676e95',
      blockquoteBackground: '#1b1e2b',
      listMarker: '#82aaff',
      tableBorder: '#3a3f58',
      tableHeaderBackground: '#1b1e2b',
      tableRowEvenBackground: '#2f3344',
      horizontalRule: '#3a3f58',
      bold: '#a6accd',
      italic: '#c792ea',
    },
  },
  {
    id: 'cobalt2',
    name: 'Cobalt2',
    isDark: true,
    colors: {
      background: '#193549',
      text: '#ffffff',
      h1: '#ffc600',
      h2: '#ff9d00',
      h3: '#3ad900',
      h4: '#9effff',
      h5: '#ff628c',
      h6: '#fb94ff',
      link: '#9effff',
      linkHover: '#80fcff',
      codeBackground: '#122738',
      codeText: '#ffffff',
      inlineCodeBackground: '#0d3a58',
      inlineCodeText: '#ff628c',
      blockquoteBorder: '#ffc600',
      blockquoteText: '#8ba7b3',
      blockquoteBackground: '#122738',
      listMarker: '#ffc600',
      tableBorder: '#0d3a58',
      tableHeaderBackground: '#122738',
      tableRowEvenBackground: '#15364d',
      horizontalRule: '#0d3a58',
      bold: '#ffffff',
      italic: '#ff9d00',
    },
  },
];
